extraction:
  cpp:
    after_prepare: 
       - export GNU_MAKE=make
       - export GIT=true 
    index:    # Customizable step used by all languages.
      build_command:
        - $GNU_MAKE sv1.exe
